### PR TITLE
Include azure as a dependency

### LINKED ISSUE #4: Cannot create Fog::Compute.new
When running this code in mock mode (have not tried with regular credentials, but I suspect it's the same)

```
azure = Fog::Compute.new(
  :provider => 'Azure',
  :azure_sub_id => '35a2461c-22ac-1111-5ed2-11165d755ba4',
  :azure_pem =>    'c:/path/abc.pem',
  :azure_api_url => 'usnorth.management.core.windows.net'
)
```

Error returned is:

```
     RuntimeError:
       cannot load such file -- Azure
```

There is an issue with the :provider

### PR DESCRIPTION
**Pull request by jntullo**
resolves #4

### CODE REVIEW

**Comment by jntullo** [comment]
also closes #6

**Comment by tbartynski** [comment]
I've also encountered the missing azure dependency problem. Adding azure gem to dependencies helped. Please merge this pull request.

**Comment by dLobatog** [comment]
I'd appreciate if you could make a new gem release including this patch - otherwise I have to embed the 'azure' dependency myself - Thanks!  :smile:

**Comment by jeffmendoza** [comment]
@dLobatog I opened #24

**Pull request merged**
