### PR TITLE
Support add_data_disk

### PR DESCRIPTION
**Pull request by noralife**
This patch enables Compute to add data disk.
Please kindly review this.

### CODE REVIEW

**Comment by noralife** [comment]
@geemus 
Thank you for reviewing patch #17 
Could you see this patch also?

I know returning nil is not appropriate for Mock.
But I found so many request methods return nil....
See below codes.

lib/fog/azure/requests/compute/delete_virtual_machine.rb

```
      class Mock
        def delete_virtual_machine(vm_name, cloud_service_name)
          nil
        end
      end
```

lib/fog/azure/requests/compute/firewall_rules.rb

```
      class Mock
        def firewall_rules(name)
          nil
        end
      end
```

lib/fog/azure/requests/compute/shutdown_server.rb

```
      class Mock
        def shutdown_server(vm_name, cloud_service_name)
          nil
        end
      end
```

**Comment by geemus** [comment]
Thanks! non-nil would probably be better, but since many other things are already busted it doesn't seem much worse. Alternatively, most of the other providers will just NOT define things where the mock isn't ready (which then just raises an error about being unimplemented if you try to call it). That would probably be a better behavior (and less surprising). What do you think?

**Comment by noralife** [comment]
I totally agree with you. I am not so familiar with other provider libraries but unimplemented error is good way to notice users that the methods are not ready. Deleting current methods which don't have mocks has a big impact to current users. So why don't we implement current mock first?

**Comment by geemus** [comment]
@noralife I meant just to delete the mock versions (which just return nil), but leave the real versions. I suspect that shouldn't impact users too much, but I could be wrong. Implementing the missing mocks would be even better, but is also more difficult and time consuming.

**Comment by noralife** [comment]
Sounds good. I will create another PR to delete Mocks which return nil.

**Comment by geemus** [comment]
Sounds like a plan, thanks!

**Pull request merged**
